name: 'Test'
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Install
        run: npm install
      - name: Run Linter
        run: npm run lint

  job_tests:
    name: Test
    needs: job_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Unit Tests
        run: npm test